name: Linting

on:
  pull_request:
    branches:
      - main
      - feat/*
      - fix/*

  push:
    branches:
      - main
      - feat/*
      - fix/*

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: SSH into the vm
        uses: appleboy/ssh-action@master
        with:
          host: 20.244.25.241
          username: azureuser
          key: ${{ secrets.ACTION_SECRET }}
          port: 22
          script: |
            cd ci-cd
            git pull origin main
            cd
            pm2 restart all